version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pagination_db
    restart: always
    environment:
      POSTGRES_USER: page
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pagination
    ports:
      - "50001:5432"
#   volumes:
#     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: "필요시"
