version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "$UID:$GID"
    ports:
      - "50003:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "50002:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus